### ISSUE TITLE
Incorrect use of PUT

### ISSUE THREAD

**Issue by davidbanham** [Prismatik/auth#14]
https://github.com/Prismatik/auth/blob/master/controllers/entities.js#L14

I think that should be a POST. At no time do we accept a user persisting an inherited_permissions array, for example. In order to satisfy the semantic requirements of PUT we would need to store the resource exactly as the user had sent it.

**Comment by Nicktho** [comment]
Fixed by https://github.com/Prismatik/auth/issues/15
